export let tasksData = [
  {
    id: 1,
    name: "Shoping list",
    created: "4/21/2021",
    category: "Task",
    content: "Tomatoes, bread",
    dates: "",
    type: "active",
  },
  {
    id: 2,
    name: "The teory of evolution",
    created: "4/27/2021",
    category: "Random Thought",
    content: "The evolution",
    dates: "",
    type: "active",
  },
  {
    id: 3,
    name: "New Feature",
    created: "3/5/2021",
    category: "Idea",
    content: "Implement new feater",
    dates: "5/5/2021",
    type: "active",
  },
  {
    id: 4,
    name: "Shoping list",
    created: "5/6/2021",
    category: "Task",
    content: "Bread, milk, tomato",
    dates: "",
    type: "active",
  },
  {
    id: 5,
    name: "About React",
    created: "5/6/2021",
    category: "Random Thought",
    content: "React evolution",
    dates: "",
    type: "active",
  },
  {
    id: 6,
    name: "New Feature",
    created: "5/7/2021",
    category: "Idea",
    content: "Implement new script",
    dates: "5/8/2021",
    type: "active",
  },
];
